name: simple_qr_scanner
description: "Simple QR Scanner"
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  permission_handler: ^11.3.1
  mobile_scanner: ^6.0.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
