name: simple_qr_scan
description: "Simple QR Scan."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  mobile_scanner: ^6.0.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
